### ISSUE TITLE
Create Ember data models

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/funzo-app#1]
These needs to be created with their relations and attributes

- [x] User
  * id
  * email
  * photo
  * register date
  * completed lessons
  * completed modules (computed?)
  * completed courses (computed?)
  * xAPI statements (has many)
- [x] Course
  * id
  *title
  *expires
  *modules (has many)
- [x] Module
  * id
  * title
  * lessons (has many)
- [ ] xAPI Statement
  * id
  * serialized statement

**Comment by Jakeii** [comment]
If anyone would like to chip in on this see this page on defining models for help https://guides.emberjs.com/v2.2.0/models/defining-models/

**Comment by usernamenumber** [comment]
Quick question: does `photo` need to be a special data type, or is it just a string that will be used to construct a url?

To put it another way: is each of the properties described here either a `DS.attrib()` with no special transform, an Ember.computed(), or a `DS.hasMany()`, or are there more complicated ones?

**Comment by Jakeii** [comment]
I'm working on the user one as part of the login work I'm doing. Photo would just be regular attr (base64 encoded image). Any relations will be has many or has one etc
