### ISSUE TITLE
Present "book" with course structure

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#108]
Instead of starting on the book, the book metadata should allow the definition of reading, watching,  and quiz activities. 

@Jakeii has done a basic prototype. Jake, can you please push that to a branch and reference it here?

**Comment by Jakeii** [comment]
This is in the course branch already. I'll add a repo for the demo course with a reading component.

But there's an issue with the h5p-standalone, as there seems to have been a change in H5P that breaks it, I've fixed it, but can't figure out a way to be backwards compatible.

changes to work with new H5Ps https://github.com/tunapanda/h5p-standalone/pull/3

issue asking how to be backwards compatible https://github.com/h5p/h5p-editor-php-library/issues/18
