### ISSUE TITLE
Encrypting the book

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/funzo-app#32]
We'll need to choose an algorithm, encrypt the book pages/html files and store the Key using something like:
https://github.com/Crypho/cordova-plugin-secure-storage

We'll also need a tool to encrypt the book before adding it to the app.

**Comment by Jakeii** [comment]
https://github.com/aerogear/aerogear-cordova-crypto

**Comment by usernamenumber** [comment]
Milestone: encrypted content is checked into the repo as of e4340c34478a6255d2b4dd28df5c1bbe3f4eddaa in the book branch. 

Content can be encrypted with a command like 

```
# Prompts for passphrase, then prints encrypted content to stdout
openssl enc -aes256 -a -in SectionXX.html
```

HTML should be generated by making manual tweaks as needed in gdocs, then downloading as HTML and running the [`process_html-3.py` script](https://gist.github.com/usernamenumber/bf648d6e7d3ffe17b12759a4ae999aa6#file-process_html-3-py) on it. 

Reasonable handling of the key for unencryption via cordova remains TODO.

**Comment by Jakeii** [comment]
closing in favour of #41
