### ISSUE TITLE
Location restriction

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/funzo-app#33]
we need to access the devices GPS/IP address and restrict features using location.

> - If the IP address shows a US/Canada location, then the student must enter a unique code proving they are "in an educational setting" ­ that code determines the length of time the student will be able to access the eBook.
> - If the IP address shows a non­US/Canada location, then the learner can download the eBook which is "charged" (the equivalent of "borrowed from the library" in the US context) for a certain period of time.

**Comment by usernamenumber** [comment]
Cordova has a [geolocation plugin that can get the device's latitude and longitude](https://cordova.apache.org/docs/en/3.0.0/cordova/geolocation/geolocation.html).

Still needed: 
* Something to convert lat/long to country code
* Ideally a way to test outside of a cordova environment
