### ISSUE TITLE
Display one page instead of two at a time?

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#35]
Especially for smaller devices, I suggest that displaying one page at a time is a better default than the current two. 

I tried setting pagesPerScreen to 1 in the places where it appears in [`book-section/component.js`](https://github.com/tunapanda/funzo-app/blob/book/app/pods/components/book-section/component.js), but it just displays the first page with no apparent ability to advance to the next, even though they are all present and properly paginated in the source.

**Comment by usernamenumber** [comment]
Tested. Works great! One note for @Jakeii before I close this, though: it your commit msg suggests that you only mean for it to display one page when in portrait mode. I'm now seeing it in both portrait and landscape. I think a single page looks fine in both views, though. Any objection to closing this now?

**Comment by Jakeii** [comment]
No go ahead, it just decides which way to go by which of page horizontal or vertical is longer.
