### ISSUE TITLE
Sections sometimes render with no content

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#36]
Not sure what causes this. No errors show up in the js console except for the usual missing cordova.js message, but blank pages are displayed. Upon further inspection, the pages were created, but not populated with content. Reloading the page generally fixes the problem, but it tends to happen the first time the section loads in particular, making for a not-great first impression.

<img width="1251" alt="screen shot 2016-05-02 at 5 43 15 pm" src="https://cloud.githubusercontent.com/assets/188349/14969871/b79a2468-1092-11e6-902f-e76acf5b6043.png">

**Comment by Jakeii** [comment]
Is this fixed for you?

**Comment by usernamenumber** [comment]
Hard to prove a negative, so I was going to use the app for another day or
so and see if it recurred, then close this if it didn't (sorry, should have
left an update saying as much).
