### ISSUE TITLE
PageClick action on whole page breaks on-page links

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#43]
Currently in the `book` branch, the whole page is associated with the `pageclick` action. This seem to override any actual links on the page. I propose moving the clickable area to only the left margin of the leftmost page, and the right margin of the rightmost, so navigate by clicking page edges.

**Comment by Jakeii** [comment]
fixed in https://github.com/tunapanda/funzo-app/commit/afd56637c2bfc88cd1f66156035cd1a15707a722
