### ISSUE TITLE
Can't click submit

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/funzo-app#49]
The submit button does not work on registration on an iPhone 4.

**Comment by usernamenumber** [comment]
Can you confirm that all fields have been filled out, and that the PIN is
just 4 numbers? The app doesn't have much error reporting yet, so my guess
is that the button is active, but something about the input is causing it
to fail silently.

**Comment by jaylarson85** [comment]
That might be it - I'm logged in now and can't log out so it's hard to say.

**Comment by Jakeii** [comment]
Okay this should be fixed in the commit above

@jaylarson85  you should be able to log out via the drop down user icon in the nav bar?

**Comment by jaylarson85** [comment]
Nothing happens when I click on "settings"... and actually now the app
isn't loading at all. might be my phone/connection.

On Mon, May 16, 2016 at 12:09 PM, Jake Lee Kennedy <notifications@github.com
