### ISSUE TITLE
Never ending pages

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/funzo-app#55]
The pages go on forever.

**Comment by neerajkamdar** [comment]
I couldn't reproduce this on my phone. 

@jaylarson85, perhaps you're using an older version of mobile safari where this is happening? 

I even tried on the mobile simulator on Xcode but could only check as far back as iPhone 4S using iOS 9.3 and it wasn't happening there. 

Could you check iOS version you're on?

**Comment by jaylarson85** [comment]
Yeah I'm on an iPhone 4 and it won't even update past 7.1.2.

**Comment by neerajkamdar** [comment]
Do we know what our minimum support requirements are? 

If we have to support iOS 7.1.2 then I can try to fix it. 

My guess is that the vh unit we use for the height is causing this bug. It was reported here: https://mjau-mjau.com/blog/ios-vh-bug/

**Comment by Jakeii** [comment]
This won't matter when its in the app because it uses an up to date chrome
based webview, so it's just what devices are they going to demo on?

**Comment by jaylarson85** [comment]
I'd say don't sweat this atm - not too many people using iPhone 4 and this
isn't a deal-breaker. I'm sure the demo will be on newer devices
