### ISSUE TITLE
Chart formatting

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/funzo-app#57]
Charts with columns run off the page and don't look good.

**Comment by neerajkamdar** [comment]
To fix this I need to add some classes to the table element. I looked in public/content/book/CSE/02-seven-major-sources-of-economic-progress.json but the book content seems to be encrypted.

Is there anyway to be able to edit the HTML for that?

**Comment by usernamenumber** [comment]
Right now the process is pretty manual (note to self that I need to
document it). For now it might be easiest if you just told me what classes
need to be added where. Is it consistent? Like, add this class to any
image, or just to particular images?

**Comment by neerajkamdar** [comment]
Ok .. I'll try to get a solution working (I can change the class names through the web inspector for testing) and then let you know what class names to add.

**Comment by usernamenumber** [comment]
I've given you access to the content. See email.

**Comment by neerajkamdar** [comment]
These column headings are too large. The best way to fix it would be abbreviate the heading and show the full form of the abbreviation below/above the table. Are we allowed to do that? Or will that be a copyright issue?

I have a solution for a responsive table but these headings are too large for that.

**Comment by usernamenumber** [comment]
should be fixed now.
