### ISSUE TITLE
Word spacing off

### ISSUE THREAD

**Issue by jaylarson85** [tunapanda/funzo-app#59]
The justification and narrow columns mean lots of spaces. Maybe decrease the width from the edges in mobile mode?

**Comment by Jakeii** [comment]
On small displays it does look odd with the large gaps, but to keep that book page feel we should keep it  justified (and it looks stranger to me left aligned). We can add hyphens with something like http://mnater.github.io/Hyphenator/ to reduce the gaps.

Also we could have the page margins use css vw and vh unit to make them proportional to the viewport size, which will increase space for text.

**Comment by Jakeii** [comment]
We will leave this for the first version, as the ebook in the kindle store isn't hyphenated.
