### ISSUE TITLE
Open footnotes in modal window

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#67]
Fred says:

>  Can the footnotes open in an new window? Or would this mess up navigation on a phone or tablet?

Should be able to roll most of this into #64, I think.

**Comment by Jakeii** [comment]
dependant on https://github.com/usernamenumber/funzo-cse/issues/4 being fixed

**Comment by usernamenumber** [comment]
Ok, that issue is now fixed. Adding `enhancement` tag, since we currently have working implementation of footnotes (though imo a modal would be much better)
