### ISSUE TITLE
h5p content

### ISSUE THREAD

**Issue by Jakeii** [tunapanda/funzo-app#7]
Move h5p content out of the repository, it will be too large and cumbersome to keep in the repo.

or perhaps git LFS could be handy here.

**Comment by limikael** [comment]
Maybe create a new repo that contains the H5P content?

**Comment by Jakeii** [comment]
@limikael yea that's probably the best way, I'll make one for the course(s), and figure out LFS for the videos and other media.

**Comment by Jakeii** [comment]
I've started using bower to add the course, but this makes installing the app really slow as it's quite large with the course inside, I think we need to figure out downloading after the app is installed.
