### ISSUE TITLE
Possible problem with transitions between sections

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#70]
Fred reports:

> There may be an issue with refreshing. As I change sections, sometimes (always?) the new section doesn’t show up on the screen until I move the window around or hit the refresh button.

I recall noticing some odd behavior when transitioning between sections linearly (moving past the last page, as opposed to using the dropdown or TOC page) as well, but more investigation is needed.

**Comment by usernamenumber** [comment]
I am not able to reproduce this so far (using desktop chrome; haven't tried on phone). Will try with app and follow-up with Fred if needed. 

@Jakeii I am seeing one odd thing: when you move forward from the last page of section N, you progress to the first page of section N+1, which makes sense. However, if you then move backward from the first page of section N+1, you end up at the *first* page of section N, not the last, which seems to me to be more intuitive. Is that the intended behavior?

**Comment by usernamenumber** [comment]
One possible cause: I notice that when you move from section N to N+1, there is a very fast animation of lots of pages whizzing past. Maybe that's too much for some mobile browsers? Would it be difficult to disable?

**Comment by Jakeii** [comment]
going back and being on the first page of the last thing certainly needs addressing.

Whizzing pages should be doable, just need to disable the css transition temporarily.

**Comment by Jakeii** [comment]
this is fixed now that all the sections are all loaded at once
