### ISSUE TITLE
Possible security issue: `isTeacher` can be modified via browser console?

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#74]
1. Install and enable the Ember Chrome extension, if needed
2. Load funzo
3. Open the Ember inspector
4. Click `Data`, then your user
5. In the data pane on the right, change `isTeacher` (or anything else)

The change doesn't seem to survive a reload of the page, but it does seem to stick around until then (e.g. if I inspect another record and then go back to the user, the changed value remains changed). 

@Jakeii, is this the inspector's UI being misleading, or an actual concern?

**Comment by Jakeii** [comment]
this can be persisted by calling `model.save()` in the console, there is no way to prevent it. But can you give an example where it would be a concern?

**Comment by usernamenumber** [comment]
Well, I assume isTeacher is intended to eventually manage some kind of
access control, right? Otherwise why distinguish between teachers and
non-teachers? In that case, isn't it essentially privilege escalation
if someone can simply change that value client-side?

**Comment by Jakeii** [comment]
Well only the teacher account can get the settings ui for managing courses,
xapi statements, and user accounts

**Comment by usernamenumber** [comment]
Given that the xapi statements represent a student's participation records, quiz scores (eventually), etc, isn't that a problem? An enterprising student could just change isTeacher and then alter their results however they like, right?

--Brad

**Comment by Jakeii** [comment]
You can't use the remote inspector on production apps, so it won't be much
of an issue there.

But any access to the console will let a user do anything they want,
including finding the LRS api key and sending whatever statements they want.
