### ISSUE TITLE
"half" page displaying

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#98]
Fred from Certell reports:

> I’m viewing on a MacBook Air with two external monitors and using Bootcamp so I’m in Windows. The columns are not centering: that is, one column is split on both right and left. When I move to the next page, I get the other half of the far right column on the far left. This makes the text unreadable in that column, and I can’t adjust it as far as I can figure out, so I miss every fourth column.

@Jakeii, might this have been addressed by your latest update? If not, can you put it on your radar?

**Comment by Jakeii** [comment]
this should be gone now #97 is merged

**Comment by usernamenumber** [comment]
Haven't seen this since. Closing.
